// Spike: generate the member manifests (and, for one class, the fully-stubbed class body) from
// the pinned declarations, so the breadth exists without anyone typing it. Emits
// generated/manifests.generated.ts and generated/fake-entity-stubs.generated.ts, then reports
// what it cost. Compile the output with: npx tsc --noEmit --strict ... generated/*.ts
// Run: node codegen-probe.mjs > codegen-probe.out.txt

import fs from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const ts = require('typescript')

const dtsPath = path.resolve('node_modules/@minecraft/server/index.d.ts')
const program = ts.createProgram([dtsPath], {
  strict: true,
  target: ts.ScriptTarget.ES2022,
  module: ts.ModuleKind.Node16,
  moduleResolution: ts.ModuleResolutionKind.Node16,
  noEmit: true,
  types: [],
})
const checker = program.getTypeChecker()
const source = program.getSourceFile(dtsPath)
const exports_ = checker.getExportsOfModule(checker.getSymbolAtLocation(source))
const classes = new Map()
for (const sym of exports_) {
  const decl = sym.declarations?.find(ts.isClassDeclaration)
  if (decl) classes.set(sym.name, { sym, decl })
}

const split = (name) => {
  const { sym, decl } = classes.get(name)
  const methods = []
  const properties = []
  for (const p of checker.getPropertiesOfType(checker.getDeclaredTypeOfSymbol(sym))) {
    const t = checker.getTypeOfSymbolAtLocation(p, decl)
    const sigs = t.getCallSignatures()
    if (sigs.length > 0) {
      const min = Math.min(...sigs.map((s) => s.getParameters().filter((x) => !checker.isOptionalParameter?.(x.valueDeclaration)).length))
      const max = Math.max(...sigs.map((s) => s.getParameters().length))
      methods.push({ name: p.name, minArity: Number.isFinite(min) ? min : 0, maxArity: max })
    } else {
      properties.push({ name: p.name })
    }
  }
  methods.sort((a, b) => a.name.localeCompare(b.name))
  properties.sort((a, b) => a.name.localeCompare(b.name))
  return { methods, properties }
}

// Every class the library fakes, by the same enumeration surface-count-probe.mjs uses.
const componentClasses = [...classes.keys()].filter((n) => /^Entity.*Component$/.test(n))
const signalsOf = (container) => {
  const { sym, decl } = classes.get(container)
  return checker
    .getPropertiesOfType(checker.getDeclaredTypeOfSymbol(sym))
    .map((p) => checker.typeToString(checker.getTypeOfSymbolAtLocation(p, decl)))
    .filter((n) => classes.has(n))
}
const faked = [
  ...new Set([
    'Entity', 'Player', 'World', 'Dimension', 'Effect', 'EffectType', 'System', 'Scoreboard',
    'ScoreboardObjective', 'ScoreboardIdentity', 'ScreenDisplay', 'WorldAfterEvents',
    'WorldBeforeEvents', 'SystemAfterEvents',
    ...componentClasses,
    ...signalsOf('WorldAfterEvents'),
    ...signalsOf('WorldBeforeEvents'),
    ...signalsOf('SystemAfterEvents'),
  ]),
]

fs.mkdirSync('generated', { recursive: true })

// ---------------------------------------------------------------------------
// 1. The manifests: names, the method/property split, and declared arity. Checked complete by
//    the compiler through `satisfies`, so a version bump that adds a member fails the build.
// ---------------------------------------------------------------------------

const lines = [
  '// GENERATED by codegen-probe.mjs from @minecraft/server 2.8.0. Do not edit.',
  '// Each manifest is checked against the declarations it came from: `satisfies` proves the',
  '// split is right and the AssertNever line proves the list is complete.',
  '',
  "import type * as MC from '@minecraft/server'",
  '',
  'type MethodsOf<T> = {',
  '  [K in keyof T]-?: NonNullable<T[K]> extends (...args: never[]) => unknown ? K : never',
  '}[keyof T]',
  'type PropertiesOf<T> = Exclude<keyof T, MethodsOf<T>>',
  'type AssertNever<T extends never> = T',
  '',
  'export interface ClassManifest<T> {',
  '  readonly methods: readonly { readonly name: MethodsOf<T>; readonly minArity: number; readonly maxArity: number }[]',
  '  readonly properties: readonly PropertiesOf<T>[]',
  '}',
  '',
]

let manifestMembers = 0
for (const name of faked) {
  const { methods, properties } = split(name)
  manifestMembers += methods.length + properties.length
  const id = name.replace(/[^A-Za-z0-9]/g, '')
  lines.push(`export const ${id}Manifest = {`)
  lines.push(
    `  methods: [${methods.map((m) => `{ name: '${m.name}', minArity: ${m.minArity}, maxArity: ${m.maxArity} }`).join(', ')}],`,
  )
  lines.push(`  properties: [${properties.map((p) => `'${p.name}'`).join(', ')}],`)
  lines.push(`} as const satisfies ClassManifest<MC.${name}>`)
  lines.push(
    `type _${id}Complete = AssertNever<Exclude<keyof MC.${name}, (typeof ${id}Manifest)['methods'][number]['name'] | (typeof ${id}Manifest)['properties'][number]>>`,
  )
  lines.push(`export type { _${id}Complete }`)
  lines.push('')
}
fs.writeFileSync('generated/manifests.generated.ts', lines.join('\n'))

// ---------------------------------------------------------------------------
// 2. The other shape: a fully-written class, every member emitted as a throwing stub. This is
//    what the hand-written-breadth option looks like when a generator types it instead.
// ---------------------------------------------------------------------------

const stubLines = [
  '// GENERATED by codegen-probe.mjs from @minecraft/server 2.8.0. Do not edit.',
  '// The whole declared surface of Entity, written out. `implements` holds the generator honest.',
  '',
  "import type * as MC from '@minecraft/server'",
  // Every exported type name, so the printed signatures resolve without qualification.
  `import type { ${exports_.map((s) => s.name).sort().join(', ')} } from '@minecraft/server'`,
  '',
  'export class NotImplementedError extends Error {}',
  '',
  'export class GeneratedFakeEntity implements MC.Entity {',
]
{
  const { sym, decl } = classes.get('Entity')
  for (const p of checker.getPropertiesOfType(checker.getDeclaredTypeOfSymbol(sym))) {
    const t = checker.getTypeOfSymbolAtLocation(p, decl)
    const sigs = t.getCallSignatures()
    const declText = p.valueDeclaration?.getText(source) ?? ''
    if (sigs.length > 0) {
      const sigText = checker.typeToString(t)
      stubLines.push(`  ${p.name}: ${sigText} = () => {`)
      stubLines.push(`    throw new NotImplementedError('Entity.${p.name}')`)
      stubLines.push('  }')
    } else {
      const readonlyMod = /^\s*readonly\b/.test(declText) ? 'readonly ' : ''
      void readonlyMod
      stubLines.push(`  get ${p.name}(): ${checker.typeToString(t)} {`)
      stubLines.push(`    throw new NotImplementedError('Entity.${p.name}')`)
      stubLines.push('  }')
    }
  }
}
stubLines.push('}')
fs.writeFileSync('generated/fake-entity-stubs.generated.ts', stubLines.join('\n'))

console.log('# Codegen probe — generating the breadth instead of typing it')
console.log('')
console.log(`typescript ${ts.version}, @minecraft/server 2.8.0`)
console.log('')
console.log(`faked classes enumerated from the declarations: ${faked.length}`)
console.log(`members covered by the generated manifests: ${manifestMembers}`)
console.log(`generated/manifests.generated.ts: ${lines.length} lines, ${fs.statSync('generated/manifests.generated.ts').size} bytes`)
console.log(
  `generated/fake-entity-stubs.generated.ts: ${stubLines.length} lines, ${fs.statSync('generated/fake-entity-stubs.generated.ts').size} bytes (Entity alone)`,
)
console.log('')
console.log('hand-written lines in either file: 0. The generator is ~150 lines of Node.')
