version: "1"
kind: application

packages:
  - path: nodejs/grinbox/server
    kind: node-service
    repo: twin-digital/opus
  - path: nodejs/grinbox/web
    kind: web-app
    repo: twin-digital/opus
  - path: nodejs/grinbox/shared
    kind: npm-library
    repo: twin-digital/opus
