name: entity-types-probe
services:
  bedrock:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      LEVEL_NAME: dev
      SERVER_NAME: entity-types-probe
      GAMEMODE: creative
      DIFFICULTY: peaceful
      ALLOW_CHEATS: "true"
      CONTENT_LOG_FILE_ENABLED: "true"
      CONTENT_LOG_CONSOLE_OUTPUT_ENABLED: "true"
      LEVEL_SEED: "1"
    volumes:
      - data:/data
volumes:
  data:
