version: "2"
kind: minecraft-addon
packages:
  - path: nodejs/minecraft/rpg-core
    kind: npm-library
    component: actors
  - path: nodejs/minecraft/rpg-core-example
    kind: minecraft-addon
    component: example
